name: Build Kivy APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar dependências do sistema
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          python3-dev \
          python3-pip \
          libssl-dev \
          libltdl-dev \
          zlib1g-dev \
          libncurses5:i386 libstdc++6:i386 zlib1g:i386

    - name: Instalar Buildozer
      run: |
        pip install --upgrade pip setuptools wheel
        pip install buildozer cython

    - name: Restaurar Keystore do Base64
      if: secrets.KEYSTORE_BASE64 != ''
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > mykeystore.jks
      env:
        KEYSTORE_BASE32: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Exportar variáveis do Release
      run: |
        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

    - name: Build APK DEBUG
      run: |
        buildozer android debug

    - name: Build APK RELEASE
      if: secrets.KEYSTORE_BASE64 != ''
      run: |
        buildozer android release

    - name: Upload APKs (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: app-kivy-builds
        path: |
          bin/*.apk
          bin/*.aab

  publish-release:
    needs: build-apk
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-kivy-builds
        path: dist/

    - name: Criar Release automá-tico
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
