name: Build Kivy APK

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar dependências do sistema
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          python3-dev \
          python3-pip \
          libssl-dev \
          libltdl-dev \
          zlib1g-dev \
          libncurses5:i386 libstdc++6:i386 zlib1g:i386

    - name: Instalar Buildozer
      run: |
        pip install --upgrade pip setuptools wheel
        pip install buildozer cython

    - name: Copiar Keystore (se existir)
      if: secrets.KEYSTORE_BASE64 != ''
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > mykeystore.jks

    - name: Ajustar buildozer.spec para Release
      run: |
        sed -i "s/# android.release_keystore =.*/android.release_keystore = mykeystore.jks/" buildozer.spec
        sed -i "s/# android.release_keystore_password =.*/android.release_keystore_password = ${{ secrets.KEYSTORE_PASSWORD }}/" buildozer.spec
        sed -i "s/# android.release_keyalias =.*/android.release_keyalias = ${{ secrets.KEY_ALIAS }}/" buildozer.spec
        sed -i "s/# android.release_keyalias_password =.*/android.release_keyalias_password = ${{ secrets.KEY_PASSWORD }}/" buildozer.spec

    - name: Build APK DEBUG
      run: |
        buildozer android debug

    - name: Build APK RELEASE
      if: secrets.KEYSTORE_BASE64 != ''
      run: |
        buildozer android release

    - name: Upload APKs como Artifact
      uses: actions/upload-artifact@v4
      
      with:
        name: app-kivy-builds
        path: |
          bin/*.apk
          bin/*.aab
          
  publish-release:
    needs: build-apk
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      
      with:
        name: app-kivy-builds
        path: ./dist

    - name: Criar Release
      uses: softprops/action-gh-release@v2
      
      with:
        files: dist/*
